- hosts: all
  tasks:  
  - name: Install libraries with homebrew
    homebrew: name={{ item }} state=present
    with_items:
      - wget
      - git
      - python
      - lftp
      - zsh
      - node
      - ruby
      - ansible
  - name: Install applications with homebrew cask
    homebrew_cask: name={{ item }} state=present
    with_items:
      - alfred
      - transmission
      - firefox
      - 1password
      - appcleaner
      - caffeine
      - dropbox
      - flux
      - google-chrome
      - istat-menus
      - iterm2
      - microsoft-office
      - nvalt
      - parallels-desktop
      - robomongo
      - slack
      - teamviewer
      - transmit
      - vagrant
      - virtualbox
      - virtualbox-extension-pack
      - viscosity
      - visual-studio-code
      - vlc
      - zoomus
      
#ToDo
# Disable Mac Clock, use iStats
